version: '3.6'
services:

  accountdb:
    image: mariadb
    networks: 
      - net_account_backend
    container_name: accountserver_database
    user: root
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=account"
      - "MYSQL_USER=accuser"
      - "MYSQL_PASSWORD=unity"
    volumes:
      - accountserver-mariadb:/var/lib/mysql
    ports:
      - 5505:3306
  
  accountadmin:
    image: adminer
    restart: always
    networks: 
      - net_account_backend
    environment: 
      ADMINER_DEFAULT_SERVER: accountdb
    ports:
      - 8081:8080

  accountserver:
    networks: 
      - net_account_backend
    build:
      network: host
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5100:80"
    depends_on: 
      - accountdb

networks:
  net_account_backend:
    name: account_backend

volumes:
  # docker volume create accountserver-mariadb
  accountserver-mariadb:
    external: true  